apiVersion: v2
description: Prometheus Stack
name: prometheus
appVersion: 1.0
version: 1.0

dependencies:
  - name: kube-prometheus-stack
    version: ^12.2.3
    repository: https://prometheus-community.github.io/helm-charts

  - name: prometheus-adapter
    version: ^2.7.0
    repository: https://prometheus-community.github.io/helm-charts

