kube-prometheus-stack:
    # To shorten the name of objects
    fullnameOverride: prometheus

    # Needed to monitor more than just monitoring chart
    # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#prometheusioscrape
    prometheus:
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 400Mi
 
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false

    grafana:
      enabled: false

    # Admission pod never finished if linkerd is injected
    # TODO: investigate why
    prometheusOperator:
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
      admissionWebhooks:
        patch:
          podAnnotations:
            linkerd.io/inject: disabled

prometheus-adapter:
    prometheus:
        url: prometheus-prometheus

