grafana:
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # FIXME: This should be provided via secret
  adminUser: admin
  adminPassword: tojezelovarno

  grafana.ini:
    users:
      allow_sign_up: false
      auto_assign_org: true
      auto_assign_org_role: Editor
    auth.proxy:
      enabled: true
      header_name: X-Auth-Request-Email
      header_property: email
      auto_sign_up: true

  serviceMonitor:
    enabled: true

  imageRenderer:
    enabled: true

  # TODO: It should have working smtp?? Do we need it for alerts?
  smtp: {}

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
      searchNamespaces: ALL
    notifiers:
      enabled: true
      searchNamespaces: ALL

  # TODO: Move to respective charts
  # it will be autodiscovered by grafana
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-prometheus.monitoring:9090
        access: proxy
        isDefault: true
        editable: false
      - name: Loki
        type: loki
        url: http://loki.monitoring:3100
        editable: false

